from sqlalchemy import Column, Integer, CHAR, String
from .database import Base_db1, Base_db2, Base_db3

class Elementary(Base_db1):
    __tablename__ = 'responses'
    id = Column(Integer, primary_key=True, autoincrement=True)
    school_code = Column(Integer, index=True)
    class_name = Column(Integer, index=True)
    section = Column(CHAR(1), index=True)
    board = Column(String(5), index=True)
    gender = Column(CHAR(1), index=True)
    lang = Column(String(15), index=True)
    rollno = Column(String(15), index=True)
    q1 = Column(CHAR(1))
    q2 = Column(CHAR(1))
    q3 = Column(CHAR(1))
    q4 = Column(CHAR(1))
    q5 = Column(CHAR(1))

class Middle(Base_db2):
    __tablename__ = 'responses'
    id = Column(Integer, primary_key=True, autoincrement=True)
    school_code = Column(Integer, index=True)
    class_name = Column(Integer, index=True)
    section = Column(CHAR(1), index=True)
    board = Column(String(5), index=True)
    gender = Column(CHAR(1), index=True)
    lang = Column(String(15), index=True)
    rollno = Column(String(15), index=True)
    q1 = Column(CHAR(1))
    q2 = Column(CHAR(1))
    q3 = Column(CHAR(1))
    q4 = Column(CHAR(1))
    q5 = Column(CHAR(1))
    q6 = Column(CHAR(1))
    q7 = Column(CHAR(1))
    q8 = Column(CHAR(1))
    q9 = Column(CHAR(1))
    q10 = Column(CHAR(1))

class High(Base_db3):
    __tablename__ = 'responses'
    id = Column(Integer, primary_key=True, autoincrement=True)
    school_code = Column(Integer, index=True)
    class_name = Column(Integer, index=True)
    section = Column(CHAR(1), index=True)
    board = Column(String(5), index=True)
    gender = Column(CHAR(1), index=True)
    lang = Column(String(15), index=True)
    rollno = Column(String(15), index=True)
    q1 = Column(CHAR(1))
    q2 = Column(CHAR(1))
    q3 = Column(CHAR(1))
    q4 = Column(CHAR(1))
    q5 = Column(CHAR(1))
    q6 = Column(CHAR(1))
    q7 = Column(CHAR(1))
    q8 = Column(CHAR(1))
    q9 = Column(CHAR(1))
    q10 = Column(CHAR(1))
    q11 = Column(CHAR(1))
    q12 = Column(CHAR(1))
    q13 = Column(CHAR(1))
    q14 = Column(CHAR(1))
    q15 = Column(CHAR(1))