from sqlalchemy import Column, Integer, String, BigInteger
from .database import Base_db1, Base_db2, Base_db3

class Elementary(Base_db1):
    __tablename__ = 'responses'
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    school_code = Column(Integer, index=True, nullable=False)
    other_name = Column(String(100), index=True, nullable=True) 
    class_name = Column(Integer, index=True, nullable=False)
    section = Column(String(1), index=True, nullable=False)
    board = Column(String, index=True, nullable=False)
    gender = Column(String(1), index=True, nullable=False)
    lang = Column(String(15), index=True, nullable=False)
    rollno = Column(String(15), index=True, nullable=False)
    q1 = Column(String(1))
    q2 = Column(String(1))
    q3 = Column(String(1))
    q4 = Column(String(1))
    q5 = Column(String(1))
    q6 = Column(String(1))
    q7 = Column(String(1))
    q8 = Column(String(1))
    q9 = Column(String(1))
    q10 = Column(String(1))
    rating = Column(Integer)

class Middle(Base_db2):
    __tablename__ = 'responses'
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    school_code = Column(Integer, index=True)
    other_name = Column(String(100), index=True, nullable=True)
    class_name = Column(Integer, index=True)
    section = Column(String(1), index=True)
    board = Column(String, index=True)
    gender = Column(String(1), index=True)
    lang = Column(String(15), index=True)
    rollno = Column(String(15), index=True)
    q1 = Column(String(1))
    q2 = Column(String(1))
    q3 = Column(String(1))
    q4 = Column(String(1))
    q5 = Column(String(1))
    q6 = Column(String(1))
    q7 = Column(String(1))
    q8 = Column(String(1))
    q9 = Column(String(1))
    q10 = Column(String(1))
    q11 = Column(String(1))
    q12 = Column(String(1))
    q13 = Column(String(1))
    q14 = Column(String(1))
    q15 = Column(String(1))
    q16 = Column(String(1))
    q17 = Column(String(1))
    q18 = Column(String(1))
    q19 = Column(String(1))
    q20 = Column(String(1))
    rating = Column(Integer)

class High(Base_db3):
    __tablename__ = 'responses'
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    school_code = Column(Integer, index=True)
    other_name = Column(String(100), index=True, nullable=True)
    class_name = Column(Integer, index=True)
    section = Column(String(1), index=True)
    board = Column(String, index=True)
    gender = Column(String(1), index=True)
    lang = Column(String(15), index=True)
    rollno = Column(String(15), index=True)
    q1 = Column(String(1))
    q2 = Column(String(1))
    q3 = Column(String(15))
    q4 = Column(String(1))
    q5 = Column(String(1))
    q6 = Column(String(1))
    q7 = Column(String(1))
    q8 = Column(String(1))
    q9 = Column(String(1))
    q10 = Column(String(1))
    q11 = Column(String(1))
    q12 = Column(String(1))
    q13 = Column(String(1))
    q14 = Column(String(1))
    q15 = Column(String(1))
    q16 = Column(String(1))
    q17 = Column(String(1))
    q18 = Column(String(1))
    q19 = Column(String(1))
    q20 = Column(String(1))
    q21 = Column(String(1))
    q22 = Column(String(1))
    q23 = Column(String(1))
    q24 = Column(String(1))
    q25 = Column(String(1))
    q26 = Column(String(1))
    q27 = Column(String(1))
    q28 = Column(String(12))
    rating = Column(Integer)